### ISSUE TITLE
No indicar punto cardinal en L' si hay contacto

### ISSUE THREAD

**Issue by jmlahoz** [agarsev/signario-web#3]
Esta consulta afecta a las convenciones de signotación pero interfiere con las reglas de búsqueda de la web. No sé si este es el lugar más apropiado para la issue.

Ejemplo: ANÉCDOTA, I:Xh:Nar:^:->\*:L PICAM:Fh:[PICAM-:Hfx]H:+:->:L\*

En el segundo morfema, la coda indica L*, pero pienso que bastaría con * (se entiende que el contacto es con el lugar indicado en el ataque, que es la H2). Pero no sé si quitar la L obliga a implementar alguna regla en el sistema de búsqueda en el caso que alguien quisiera especificarlo. Por otro lado, siempre que haya un modificador de posición relativa con respecto al lugar en el ataque, como aquí [ ]H, se predice que la dirección del movimiento es siempre la opuesta. Pero esa posición relativa no siempre se especifica, p. ej. cuando H1 está en [ ]Y, que es lo natural.

¿Puedo asumir la convención signotadora de poner solo * en este tipo de casos?

**Comment by jmlahoz** [comment]
¿Entonces hay lugares que tú no pondrías hasta la coda, incluso si el lugar está "preparado" desde el ataque? Otro ejemplo sería [AÑADIR](https://griffos.filol.ucm.es/signario/signo/11495).

**Comment by agarsev** [comment]
Sí, justo
